### ISSUE TITLE
Search Assets by ROI

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C098#23]
Similar to the query form 

Spatial filter available are:
- Viewport
- BBOX
- Circle
- Polygon

**Comment by tdipisa** [comment]
Asset geom is not mandatory and we need to ask the sciadro backend to retrieve the list of assets within the defined ROI and then use the returned ids list to further filter assets client side

**Comment by tdipisa** [comment]
closed for inactivity
