### ISSUE TITLE
BBOX query param - Client installation

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#3]
A bbox queryparam is needed in MS2 to zoom the map to a specific extent at startup.
An additional option to the sharable map link should be added to include the bbox parameter as query param, the value conresponds to the current extent in the viewport. 

connected to geosolutions-it/MapStore2#3545

**Comment by allyoucanmap** [comment]
connected to https://github.com/geosolutions-it/MapStore2/issues/3545

**Comment by tdipisa** [comment]
@allyoucanmap , we need to update the MS2 revision for thisto the 2019.01.xx when the MS2's commit will be backported to the stable branch (after the incoming release).
