### ISSUE TITLE
Image Mosaic - Time Series

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#73]
The **Servizio Idrologico** of Regione Toscana needs support for the deploy (preparation, configuration and tuning) of Temporal Image Mosaics in GeoServer. 

The **Servizio Idrologico** produces 1 raster file per day: one file for each relevant variable in which the monitoring values come from regional sensors disseminated in Tuscany (variable are temperature min/max, rain, evapotraspirazione). The produced raster file (Geotiff) is related to the monitoring on the day before (a lifecycle of 30-days must be guranteed, so for each month we have 30-31 files).

The client has provided to GeoSolutions some sample files related to **rain data** collected during one month (the zip file containing this data is available [here](https://drive.google.com/drive/u/0/folders/1SG4LCdms-mCWw2OLHiMcI7yJIWo2UfZb)).

GeoSolutions has to configure a temporal image mosaic in the client's GeoServer so the client (along with the provided documentation that describes the configuration steps of the mosaic) can check it and learn a little bit better the creation procedure of temporal mosaics to be autonomous in the future. 

The general purpose of this for the client, is to finally have multiple temporal mosaics in GeoServer (one for each variable) that can be used with the MS Timeline.

We can configure the sample mosaic in the SIR GeoServer (the documentation to access the machine is available in GDrive).

**Comment by tdipisa** [comment]
@Gnafu this is the issue I created for Servizio idrologico of Regione Toscana that we still have to schedule.
Please follow @ElenaGallo for this, @ElenaGallo let's check if the Test machine is still available before replicating this work on production.

**Comment by chpicone** [comment]
@Gnafu can you check the data (annual) produced by @ElenaGallo?
[folder](https://drive.google.com/drive/folders/1wFWv0lPiDUSUmf-sweERd4jkyWvXmCsY)
So, she can continue with the elaboration of the monthly data...

**Comment by chpicone** [comment]
I sent email with teh final [documentation ](url)![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/bce038a9-d72c-4ceb-95f9-2240e4e9c117) to the customer.
