### ISSUE TITLE
Prepare MS project

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C098#78]
We need to prepare the MS project for Servizio Idrologico containing the last stable version of MS (with the tooltip map hover capabilities).

**Comment by chpicone** [comment]
As discussed with @tdipisa this task could be completed in the early July (2/3)

**Comment by tdipisa** [comment]
@MV88 can you please update this MS down stream project (**sidro** branch) to the last MS stable (2020.02.00)?
It would be useful if you can take a look at [this](https://github.com/geosolutions-it/MapStore2/issues/5562) issue at the same time or right after this.

**Comment by MV88** [comment]
i'll wait the review from @allyoucanmap for creating and pushing somewhere the **.war**

**Comment by tdipisa** [comment]
@MV88 the PR is merged, please provide the war as soon as you can. Thank you.
