### ISSUE TITLE
End 2 End tests

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C098#79]
we need to test all MS functionality and the new tooltip with the map "hover" event.

**Comment by randomorder** [comment]
note that the default maps won't work because they point to the production GeoServer
You'll have to test against the test GeoServer which should be http://10.159.212.210/geoserver (right, @giacomoc92 ?)

**Comment by giacomoc92** [comment]
This is correct

**Comment by ElenaGallo** [comment]
[Here](https://docs.google.com/spreadsheets/d/1Z7GzepxiVlpDwTJhSX0b23DB2ONC1HfBJ-Bni2WrX0U/edit#gid=376642658) the spreadsheet with the testing results.

**Comment by chpicone** [comment]
@MV88 please take a look to the issues in the comment above?

**Comment by chpicone** [comment]
@tdipisa please, can you ask someone to take a look to these issues?

**Comment by tdipisa** [comment]
@MV88 can you please take a look at the issues reported in the test spreadsheet linked above? There are just few minor issues that probably we will be able to solve simply updating the MS git submodule revision.

**Comment by MV88** [comment]
i've updated the spreadsheet with my notes

**Comment by chpicone** [comment]
@ElenaGallo can you test the new installed version?

**Comment by ElenaGallo** [comment]
@chpicone I ran the tests, the last issues ([here](https://docs.google.com/spreadsheets/d/1Z7GzepxiVlpDwTJhSX0b23DB2ONC1HfBJ-Bni2WrX0U/edit#gid=376642658)) have passed.

**Comment by chpicone** [comment]
@ElenaGallo ok, fine!
