### ISSUE TITLE
Install new MS version in Test Environment

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C098#86]
We need to install the new version of MapStore (branch sidro) containing the new MapTip functionality in the test environment of Regione Toscana (Servizio Idrologico).
When someone is available to do this task let me know to talk with the customer to set a date/time for the installation

**Comment by chpicone** [comment]
@randomorder when installation is done let me know so I will make specific tests

**Comment by randomorder** [comment]
Ready for deployment? Where can we fetch the war file?

**Comment by chpicone** [comment]
@randomorder I built the war and put it into the shared folder [\\192.168.1.87\Public\GeoSolutions\REGIONE TOSCANA](\\192.168.1.87\Public\GeoSolutions\REGIONE TOSCANA)

**Comment by randomorder** [comment]
thanks, @giacomoc92 will perform the setup on the test machine today

**Comment by chpicone** [comment]
@randomorder @giacomoc92 can I know when? I need to inform the customer.

**Comment by randomorder** [comment]
for the setup on the test machine? It should not impact them.. Anyway, @giacomoc92 ?

**Comment by giacomoc92** [comment]
I am downloading the .war, ~5 minutes left. I will proceed with the deploy as soon as it's done

**Comment by chpicone** [comment]
@giacomoc92 let me write to the customer to set a time for the deploy.

**Comment by chpicone** [comment]
@giacomoc92 you can proceed

**Comment by giacomoc92** [comment]
New mapstore has been deployed on test, access it at http://10.159.212.210/mapstore/#/

As usual  make sure to be connected to their VPN fist https://drive.google.com/file/d/1O67wS1bAEE4BpBtcBJk6spekAcCgU8pj/view

**Comment by chpicone** [comment]
@giacomoc92 I make tests for MapTip and it is working for me.

**Comment by giacomoc92** [comment]
Can we move on with the deploy on TIX? @chpicone

**Comment by chpicone** [comment]
Customer said that this version is good!
We can move the production environment (please, see this issue #87 ).
