### ISSUE TITLE
Install new version of MS in the PROD environment

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2-C098#87]
@chpicone commented on [Wed Sep 30 2020](https://github.com/geosolutions-it/MapStore2-C013/issues/37)

Install the new version of MS with MapTip functionality in the PROD environemt of the customer

---

@chpicone commented on [Wed Sep 30 2020](https://github.com/geosolutions-it/MapStore2-C013/issues/37#issuecomment-701226112)

/remind me on friday

---

@reminders[bot] commented on [Wed Sep 30 2020](https://github.com/geosolutions-it/MapStore2-C013/issues/37#issuecomment-701226146)

@chpicone set a reminder for **Oct 2nd 2020**

**Comment by chpicone** [comment]
@randomorder we can move it to the PROD environment.
Please let me know when someone can work on it to schedule a date/time with the customer.

**Comment by giacomoc92** [comment]
New mapstore has been deployed at http://webgis.sir.toscana.it/mapstore/#/ @chpicone 

changes logged to the machine's document as usual https://docs.google.com/document/d/1kVtJspPSLZZkvZFOLatZXZIZ-FsLBsLnJHYCI8lbTk8/edit#heading=h.xzyb3emwye5d

**Comment by chpicone** [comment]
ok thx @giacomoc92 
I made some tests about MapTip and it is works for me.
I will close the issue.
