### ISSUE TITLE
Aggiornamento MapStore a 2022.02.01 su 10.159.212.111

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2-C098#90]
Al momento (30/11/2022) la versione di MapStore in uso al cliente all'IP sopraindicato e' [v2019.01.00](https://github.com/geosolutions-it/MapStore2/tree/v2019.01.00).

**Comment by offtherailz** [comment]
We should:
- make `sidro` the default branch on github
- update accordingly to the migration guidelines. https://github.com/geosolutions-it/MapStore2-C098/blob/sidro/module-replacements.webpack.js 
- The branch `sidro` is newer, so we need to update the issue description
- update, clean up and document overrides applied using `NormalModuleReplacements` plugin https://github.com/geosolutions-it/MapStore2-C098/blob/sidro/module-replacements.webpack.js
